import type { ReviewFinding, ReviewResult } from '../protocols/review-result.js';

function valueOrNA(value: string | undefined): string {
  const normalized = value?.trim();
  return normalized ? normalized : 'N/A';
}

function renderFinding(finding: ReviewFinding, index: number): string {
  return [
    `### ${index + 1}. ${finding.severity}`,
    '',
    `- File: ${valueOrNA(finding.file)}`,
    `- Problem: ${finding.problem}`,
    `- Required Fix: ${valueOrNA(finding.requiredFix)}`,
  ].join('\n');
}

export function generateReviewSummary(review: ReviewResult): string {
  const findings =
    review.findings.length === 0
      ? '无结构化问题。'
      : review.findings.map((finding, index) => renderFinding(finding, index)).join('\n\n');

  return `${[
    '# Review Summary',
    '',
    '> Generated by AgentFlow. Do not edit manually.',
    '',
    '## Step',
    '',
    `- Step ID: ${review.stepId}`,
    `- Run ID: ${review.runId}`,
    `- Verdict: ${review.verdict}`,
    `- Suggested Next Action: ${review.suggestedNextAction}`,
    '',
    '## Summary',
    '',
    review.summary,
    '',
    '## Findings',
    '',
    findings,
    '',
    '## Next',
    '',
    '根据 ReviewResult 生成 Fix Packet / Replan Packet，或由开发者人工处理。',
  ].join('\n')}\n`;
}
