import type { CheckpointDecision, CheckpointEvidence } from './checkpoint-state.js';

export type CheckpointSummaryInput = {
  stepId: string;
  runId: string;
  checkedAt: string;
  decision: CheckpointDecision;
  evidence: CheckpointEvidence;
  commitMessage: string;
};

export function generateCheckpointSummary(input: CheckpointSummaryInput): string {
  const { stepId, runId, checkedAt, decision, evidence, commitMessage } = input;
  const taskGoal = evidence.task?.goal ?? 'N/A';
  const tests = evidence.tests;
  const review = evidence.review;
  const git = evidence.git;
  const sensitiveFiles = git?.safety.sensitiveFilesDetected ?? [];
  const warnings = decision.warnings.length > 0 ? decision.warnings : ['None.'];
  const blockingReasons = decision.blockingReasons.length > 0 ? decision.blockingReasons : ['None.'];
  const missingItems = evidence.missingItems.length > 0 ? evidence.missingItems : ['None.'];

  return `# Checkpoint Summary

> Generated by AgentFlow. Do not edit manually.

## Step

- Step ID: ${stepId}
- Run ID: ${runId}
- Status: ${decision.status}
- Checked At: ${checkedAt}

## Goal

${taskGoal}

## Verification

- Status: ${tests?.status ?? 'missing'}
- Commands: ${tests?.summary.total ?? 'N/A'}
- Passed: ${tests?.summary.passed ?? 'N/A'}
- Failed: ${tests?.summary.failed ?? 'N/A'}

## Review

- Verdict: ${review?.verdict ?? 'missing'}
- Findings: ${review?.findings.length ?? 'N/A'}
- Suggested Next Action: ${review?.suggestedNextAction ?? 'N/A'}

## Git Evidence

- Repository: ${git ? String(git.isGitRepository) : 'missing'}
- Branch: ${git?.branch || 'N/A'}
- Changed Files: ${git?.changedFiles.length ?? 'N/A'}
- Has Uncommitted Changes: ${git ? String(git.hasUncommittedChanges) : 'N/A'}

### Changed Files

${formatList(git?.changedFiles ?? [])}

## Safety

- Sensitive Files Detected: ${sensitiveFiles.length > 0 ? sensitiveFiles.join(', ') : 'none'}
- Warnings: ${decision.warnings.length > 0 ? decision.warnings.length : 'none'}

## Missing Items

${formatList(missingItems)}

## Warnings

${formatList(warnings)}

## Blocking Reasons

${formatList(blockingReasons)}

## Suggested Commit Message

\`\`\`text
${commitMessage}
\`\`\`

## Next Manual Commands

\`\`\`bash
git add .
git status --short
git commit -m "${escapeForDoubleQuotedShell(commitMessage)}"
\`\`\`
`;
}

function formatList(items: string[]): string {
  if (items.length === 0) return 'None.';
  if (items.length === 1 && items[0] === 'None.') return 'None.';
  return items.map((item) => `- ${item}`).join('\n');
}

function escapeForDoubleQuotedShell(value: string): string {
  return value.replace(/\\/g, '\\\\').replace(/"/g, '\\"');
}
