import type { ReviewFinding, ReviewResult } from '../protocols/review-result.js';

function valueOrNA(value: string | undefined): string {
  const normalized = value?.trim();
  return normalized ? normalized : 'N/A';
}

function renderFinding(finding: ReviewFinding, index: number): string {
  return [
    `### ${index + 1}. ${finding.severity}`,
    '',
    `- File: ${valueOrNA(finding.file)}`,
    `- Problem: ${finding.problem}`,
    `- Required Fix: ${valueOrNA(finding.requiredFix)}`,
  ].join('\n');
}

export function generateFixSummary(review: ReviewResult, newRunId: string): string {
  const findings = review.findings.length > 0
    ? review.findings.map(renderFinding).join('\n\n')
    : '暂无结构化 finding，但本次 fix 仍来源于审查结论。';

  return `${[
    '# Fix Task from Review',
    '',
    '> Generated by AgentFlow. Do not edit manually unless you know what you are doing.',
    '',
    '## Source',
    '',
    `- Step ID: ${review.stepId}`,
    `- Source Run ID: ${review.runId}`,
    `- New Run ID: ${newRunId}`,
    `- Verdict: ${review.verdict}`,
    '',
    '## Fix Goal',
    '',
    `修复 ${review.stepId}/${review.runId} 审查中发现的问题。`,
    '',
    '## Findings to Fix',
    '',
    findings,
    '',
    '## Constraints',
    '',
    '- 只修复上述审查问题。',
    '- 不扩大原始 Step 范围。',
    '- 不提交密钥。',
    '- 修复后重新执行验收命令。',
    '',
    '## Next Commands',
    '',
    '```bash',
    `npm run dev -- approve ${review.stepId}`,
    `npm run dev -- export-task ${review.stepId}`,
    '```',
  ].join('\n')}\n`;
}
