import type { ReviewFinding, ReviewResult } from '../protocols/review-result.js';

function valueOrNA(value: string | undefined): string {
  const normalized = value?.trim();
  return normalized ? normalized : 'N/A';
}

function renderFinding(finding: ReviewFinding, index: number): string {
  return [
    `### ${index + 1}. ${finding.severity}`,
    '',
    `- File: ${valueOrNA(finding.file)}`,
    `- Problem: ${finding.problem}`,
    `- Required Fix: ${valueOrNA(finding.requiredFix)}`,
  ].join('\n');
}

export function generateReplanRequest(review: ReviewResult): string {
  const findings = review.findings.length > 0
    ? review.findings.map(renderFinding).join('\n\n')
    : '暂无结构化 finding，请 Planner 结合 ReviewResult summary 判断重规划原因。';

  return `${[
    '# Replan Request',
    '',
    '> Generated by AgentFlow. Do not edit manually unless you know what you are doing.',
    '',
    '## Source',
    '',
    `- Step ID: ${review.stepId}`,
    `- Source Run ID: ${review.runId}`,
    `- Verdict: ${review.verdict}`,
    '',
    '## Reason',
    '',
    review.summary,
    '',
    '## Findings',
    '',
    findings,
    '',
    '## Recommended Replan Direction',
    '',
    '请 Planner 基于原始 task.json、review.json、tests.json、git.json 和 context-pack.md 重新生成更小、更清晰的 Step。',
    '',
    '## Suggested Context Files',
    '',
    `- .agent/steps/${review.stepId}/runs/${review.runId}/task.json`,
    `- .agent/steps/${review.stepId}/runs/${review.runId}/review.json`,
    `- .agent/steps/${review.stepId}/runs/${review.runId}/tests.json`,
    `- .agent/steps/${review.stepId}/runs/${review.runId}/git.json`,
    '- .agent/generated/context-pack.md',
  ].join('\n')}\n`;
}
