import { readFile } from 'node:fs/promises';
import path from 'node:path';
import { isSensitivePath } from '../git/git-inspector.js';
import { taskPacketSchema, type TaskPacket } from '../protocols/index.js';
import { pathExists } from '../utils/fs.js';
import {
  getExecutionPromptPath,
  getRunDirectory,
  getTaskPacketPath,
  readStepState,
  writeText,
} from '../workflow/step-store.js';

export type ExecutionPromptResult = {
  stepId: string;
  runId: string;
  promptPath: string;
};

type ContextStatus = {
  path: string;
  status: 'found' | 'not_found' | 'sensitive_omitted';
};

type FixContext = {
  isFixRun: boolean;
  sourceRunId?: string;
  fixSummary: string;
  reviewSummary: string;
  reviewJson: string;
};

export async function createExecutionPrompt(stepId: string): Promise<ExecutionPromptResult | undefined> {
  const state = await readStepState(stepId);
  if (!state) return undefined;

  const runId = state.currentRunId;
  const taskPath = getTaskPacketPath(stepId, runId);
  if (!(await pathExists(taskPath))) {
    throw new Error(`TaskPacket not found: ${path.relative(process.cwd(), taskPath)}`);
  }

  const task = taskPacketSchema.parse(JSON.parse(await readFile(taskPath, 'utf8')));
  const promptPath = getExecutionPromptPath(stepId, runId);
  const contextStatus = await collectContextStatus(stepId, runId, task);
  const fixContext = await collectFixContext(stepId, runId, state.fixSourceRunId);

  await writeText(promptPath, renderExecutionPrompt({ task, contextStatus, fixContext }));

  return { stepId, runId, promptPath };
}

async function collectContextStatus(stepId: string, runId: string, task: TaskPacket): Promise<ContextStatus[]> {
  const paths = new Set<string>([
    'AGENTS.md',
    'README.md',
    '.agent/generated/context-pack.md',
    `.agent/steps/${stepId}/runs/${runId}/task.json`,
    ...task.contextFiles,
  ]);

  const result: ContextStatus[] = [];
  for (const relativePath of paths) {
    result.push({
      path: relativePath,
      status: await getContextStatus(relativePath),
    });
  }
  return result;
}

async function getContextStatus(relativePath: string): Promise<ContextStatus['status']> {
  if (isSensitivePath(relativePath)) return 'sensitive_omitted';
  return (await pathExists(path.resolve(relativePath))) ? 'found' : 'not_found';
}

async function collectFixContext(stepId: string, runId: string, sourceRunId?: string): Promise<FixContext> {
  const runDir = getRunDirectory(stepId, runId);
  const fixSummary = await readPromptEvidence(path.join(runDir, 'fix-from-review.md'));
  const isFixRun = fixSummary !== '_Not found_';
  const effectiveSourceRunId = sourceRunId ?? previousRunId(runId);
  const sourceRunDir = effectiveSourceRunId ? getRunDirectory(stepId, effectiveSourceRunId) : undefined;

  return {
    isFixRun,
    sourceRunId: effectiveSourceRunId,
    fixSummary,
    reviewSummary: sourceRunDir ? await readPromptEvidence(path.join(sourceRunDir, 'review-summary.md')) : '_Not found_',
    reviewJson: sourceRunDir ? await readPromptEvidence(path.join(sourceRunDir, 'review.json')) : '_Not found_',
  };
}

function previousRunId(runId: string): string | undefined {
  const match = /^R(\d+)$/.exec(runId);
  if (!match) return undefined;
  const value = Number(match[1]);
  if (value <= 1) return undefined;
  return `R${String(value - 1).padStart(3, '0')}`;
}

async function readPromptEvidence(targetPath: string): Promise<string> {
  const relativePath = path.relative(process.cwd(), targetPath);
  if (isSensitivePath(relativePath)) return '_Sensitive file omitted_';

  try {
    return await readFile(targetPath, 'utf8');
  } catch (error: unknown) {
    if (isNodeError(error) && error.code === 'ENOENT') return '_Not found_';
    throw error;
  }
}

function renderExecutionPrompt(input: {
  task: TaskPacket;
  contextStatus: ContextStatus[];
  fixContext: FixContext;
}): string {
  const { task, contextStatus, fixContext } = input;
  const runId = task.runId ?? 'R001';
  const acceptanceCommands = task.acceptanceCommands.length > 0 ? task.acceptanceCommands : ['npm run build'];

  return `# Execution Request

> Generated by AgentFlow.

## Role

你是本地代码执行器。你可以修改当前项目代码、运行命令、检查测试结果，但不能直接推进 AgentFlow 状态，不能自动 commit，不能自动 push。

## Step

- Step ID: ${task.stepId}
- Run ID: ${runId}
- Goal: ${task.goal}

## Required Context

请先阅读以下文件：

${contextStatus.map(renderContextStatus).join('\n')}

如果必需文件不存在，请停止并报告 blocker。\`.agent/generated/context-pack.md\` 缺失时不要崩溃，可以继续基于 TaskPacket 和项目文件判断。

## TaskPacket

\`\`\`json
${JSON.stringify(task, null, 2)}
\`\`\`

## Scope

${renderList(task.scope)}

## Out of Scope

${renderList(task.outOfScope)}

## Constraints

${renderList(task.constraints)}

## Acceptance Commands

请在完成修改后运行：

\`\`\`bash
${acceptanceCommands.join('\n')}
\`\`\`

${renderFixContext(task.stepId, runId, fixContext)}

## Windows Encoding Rule

If you need to read text files on Windows, use UTF-8 explicitly:

\`\`\`powershell
Get-Content -Raw -Encoding UTF8 <path>
\`\`\`

Do not use plain \`Get-Content -Raw <path>\` for Chinese UTF-8 files, because Windows PowerShell may decode them incorrectly.

## Execution Rules

1. 只完成当前 TaskPacket 的 scope。
2. 不要扩大需求范围。
3. 不要做无关大重构。
4. 不要提交密钥、token、证书或 \`.env\` 内容。
5. 不要修改 \`.agent/generated\` 下的生成文件，除非任务明确要求。
6. 不要自动 git commit。
7. 不要自动 git push。
8. 不要越过当前项目工作目录。
9. 如果遇到阻塞，停止并报告 blocker。
10. 完成后请输出 ExecutionResult JSON。

## Required Output

请最后输出一个 ExecutionResult JSON，格式如下：

\`\`\`json
{
  "protocolVersion": "agentflow.v1",
  "stepId": "${task.stepId}",
  "runId": "${runId}",
  "status": "completed | failed | blocked",
  "summary": "...",
  "filesChanged": ["..."],
  "tests": [
    {
      "command": "...",
      "passed": 0,
      "failed": 0,
      "skipped": 0,
      "rawOutput": "..."
    }
  ],
  "deviations": [],
  "blockers": [],
  "remainingRisks": [],
  "suggestedNextAction": "review | fix | replan | manual",
  "createdAt": "ISO string"
}
\`\`\`

## After Execution

执行完成后，用户会运行：

\`\`\`bash
agentflow import-result <execution-result.json>
agentflow verify ${task.stepId}
agentflow git-check ${task.stepId}
agentflow make-review-prompt ${task.stepId}
\`\`\`
`;
}

function renderContextStatus(item: ContextStatus): string {
  if (item.status === 'found') return `- ${item.path}`;
  if (item.status === 'sensitive_omitted') return `- ${item.path} - _Sensitive file omitted_`;
  return `- ${item.path} - _Not found_`;
}

function renderList(items: string[]): string {
  return items.length > 0 ? items.map((item) => `- ${item}`).join('\n') : '- _Not specified_';
}

function renderFixContext(stepId: string, runId: string, fixContext: FixContext): string {
  if (!fixContext.isFixRun) return '';

  const sourceRunId = fixContext.sourceRunId ?? 'previous run';
  return `## Fix Context

当前任务是根据上一轮 ReviewResult 生成的修复任务。

请重点阅读：

- .agent/steps/${stepId}/runs/${runId}/fix-from-review.md
- .agent/steps/${stepId}/runs/${sourceRunId}/review-summary.md
- .agent/steps/${stepId}/runs/${sourceRunId}/review.json

修复要求：

1. 只修复 review findings 中列出的问题。
2. 不要扩大原始 Step 范围。
3. 修复后重新运行 acceptanceCommands。

### fix-from-review.md

\`\`\`md
${fixContext.fixSummary}
\`\`\`

### Previous review-summary.md

\`\`\`md
${fixContext.reviewSummary}
\`\`\`

### Previous review.json

\`\`\`json
${fixContext.reviewJson}
\`\`\`
`;
}

function isNodeError(error: unknown): error is NodeJS.ErrnoException {
  return error instanceof Error && 'code' in error;
}
