import path from 'node:path';
import { AGENT_DIRECTORY, getAgentDirectory } from '../utils/path.js';
import { createDirectory, pathExists, writeFileIfMissing } from '../utils/fs.js';

const directories = ['project', 'steps', 'decisions', 'generated'] as const;

const initialFiles: Readonly<Record<string, string>> = {
  'config.yaml': `# AgentFlow project configuration\nversion: 1\nstatus: initialized\n`,
  'project/vision.md': `# 项目愿景\n\n这里记录项目的长期目标、使用场景和最终希望达到的效果。\n`,
  'project/architecture.md': `# 项目架构\n\n这里记录项目的核心模块、技术选型、目录结构和关键流程。\n`,
  'project/constraints.md': `# 项目约束\n\n这里记录开发约束、安全规则、禁止事项和代码风格要求。\n`,
  'generated/current-state.md': `# Current State\n\n> Generated by AgentFlow. Do not edit manually.\n\nStatus: initialized\n`,
  'generated/context-pack.md': `# AgentFlow Context Pack\n\n> Generated by AgentFlow. Do not edit manually.\n\nRun \`agentflow build-context\` to regenerate this file.\n`,
};

const agentsTemplate = `# AGENTS.md

## 项目开发规则

- 修改代码前先理解当前结构和已有约定。
- 保持变更范围清晰，避免大范围重构无关代码。
- 每个 Step 都需要有清晰的验收结果。

## AI 执行约束

- 不要提交密钥、令牌、证书或其他敏感信息。
- 不要读取或打包 .env、密钥文件、node_modules、dist、target 等敏感或生成目录。
- 不要在未明确要求时自动修改业务代码。
- 对外部工具、执行结果和失败原因保持可追溯记录。
`;

export async function initCommand(): Promise<void> {
  const root = getAgentDirectory();
  const alreadyInitialized = await pathExists(root);

  if (!alreadyInitialized) {
    await createDirectory(root);
  }

  for (const directory of directories) {
    await createDirectory(path.join(root, directory));
  }

  let createdFiles = 0;
  for (const [relativePath, content] of Object.entries(initialFiles)) {
    const created = await writeFileIfMissing(path.join(root, relativePath), content);
    if (created) {
      createdFiles += 1;
    }
  }

  if (await writeFileIfMissing(path.join(process.cwd(), 'AGENTS.md'), agentsTemplate)) {
    createdFiles += 1;
  }

  if (alreadyInitialized) {
    console.log(`AgentFlow is already initialized (${AGENT_DIRECTORY} already exists).`);
    console.log(`Checked memory layout and created ${createdFiles} missing file(s).`);
    return;
  }

  console.log('AgentFlow initialized successfully.');
  console.log(`Created ${AGENT_DIRECTORY} in ${process.cwd()}`);
}
