import path from 'node:path';
import { buildContext } from '../memory/context-builder.js';
import { toProjectRelative } from '../memory/memory-layout.js';
import { getAgentDirectory } from '../utils/path.js';
import { writeText } from '../workflow/step-store.js';

export type WebPlanPromptResult = {
  promptPath: string;
  contextPackPath: string;
};

export async function createWebPlanPrompt(goal: string): Promise<WebPlanPromptResult> {
  const context = await buildContext();
  const promptPath = path.join(getAgentDirectory(), 'generated', 'web-plan-request.md');

  await writeText(promptPath, renderWebPlanPrompt(goal, toProjectRelative(context.contextPackPath)));

  return {
    promptPath,
    contextPackPath: context.contextPackPath,
  };
}

function renderWebPlanPrompt(goal: string, contextPackPath: string): string {
  return `# Web Plan Request

> Generated by AgentFlow.

## Role

你是项目 Planner。你不直接修改代码，只负责根据项目上下文和用户目标生成结构化开发计划。Web AI 只提供规划建议，不推进 AgentFlow 状态，也不执行命令。

## User Goal

${goal}

## Context Files

请参考以下上下文：

- ${contextPackPath}
- AGENTS.md
- README.md

## Required Output

请输出一份 Web Plan，必须包含以下部分：

1. Goal
2. Background
3. Scope
4. Out of Scope
5. Acceptance Commands
6. Constraints
7. Risks
8. Suggested Step Title
9. TaskPacket JSON Candidate

## TaskPacket JSON Candidate 要求

请尽量输出符合 AgentFlow TaskPacket 的 JSON，但不要填写 \`protocolVersion\`、\`stepId\`、\`runId\`、\`createdAt\`。这些系统字段由 AgentFlow 在 \`import-web-plan\` 时补齐并校验。

JSON 至少包含：

\`\`\`json
{
  "goal": "...",
  "background": "...",
  "scope": ["..."],
  "outOfScope": ["..."],
  "contextFiles": [".agent/generated/context-pack.md"],
  "constraints": ["..."],
  "acceptanceCommands": ["npm run build"],
  "requiresApproval": true
}
\`\`\`

## Safety Rules

- 不要要求读取 .env、密钥、token、私有证书。
- 不要提出大范围无关重构。
- 每个 Step 必须可独立验收。
- 输出内容要便于转换成 TaskPacket。
- Web AI 不直接修改业务代码，不调用 Codex，不调用 AgentFlow 状态推进命令。
`;
}
