import { readFile } from 'node:fs/promises';
import path from 'node:path';
import { isSensitivePath } from '../git/git-inspector.js';
import { getRunDirectory, readStepState, writeText } from '../workflow/step-store.js';

const maxDiffChars = 60000;

export type WebReviewPromptResult = {
  stepId: string;
  runId: string;
  promptPath: string;
};

export async function createWebReviewPrompt(stepId: string): Promise<WebReviewPromptResult | undefined> {
  const state = await readStepState(stepId);
  if (!state) return undefined;

  const runId = state.currentRunId;
  const runDir = getRunDirectory(stepId, runId);
  const evidence = await collectEvidence(runDir);
  const promptPath = path.join(runDir, 'web-review-request.md');

  await writeText(promptPath, renderWebReviewPrompt(stepId, runId, evidence));

  return { stepId, runId, promptPath };
}

type Evidence = {
  task: string;
  tests: string;
  git: string;
  gitWarnings: string[];
  diff: string;
  executionResult: string;
  checkpoint: string;
};

async function collectEvidence(runDir: string): Promise<Evidence> {
  const git = await readEvidenceFile(runDir, 'git.json');
  return {
    task: await readEvidenceFile(runDir, 'task.json'),
    tests: await readEvidenceFile(runDir, 'tests.json'),
    git,
    gitWarnings: collectGitWarnings(git),
    diff: await readDiffEvidence(runDir),
    executionResult: await readEvidenceFile(runDir, 'execution-result.json'),
    checkpoint: await readEvidenceFile(runDir, 'checkpoint-summary.md'),
  };
}

async function readEvidenceFile(runDir: string, fileName: string): Promise<string> {
  if (isSensitivePath(fileName)) return '_Sensitive file omitted_';

  try {
    return await readFile(path.join(runDir, fileName), 'utf8');
  } catch (error: unknown) {
    if (isNodeError(error) && error.code === 'ENOENT') return '_Not found_';
    throw error;
  }
}

async function readDiffEvidence(runDir: string): Promise<string> {
  const diff = await readEvidenceFile(runDir, 'git-diff.patch');
  if (diff === '_Not found_' || diff.length <= maxDiffChars) return diff;

  return `${diff.slice(0, maxDiffChars)}\n\n_Truncated by AgentFlow: diff exceeded ${maxDiffChars} characters._`;
}

function collectGitWarnings(gitSource: string): string[] {
  if (gitSource === '_Not found_') return [];

  try {
    const data = JSON.parse(gitSource) as { safety?: { warnings?: unknown } };
    const warnings = data.safety?.warnings;
    return Array.isArray(warnings) ? warnings.filter((item): item is string => typeof item === 'string') : [];
  } catch {
    return [];
  }
}

function renderWebReviewPrompt(stepId: string, runId: string, evidence: Evidence): string {
  return `# Web Review Request

> Generated by AgentFlow.

## Role

你是独立 Reviewer。你不直接修改代码，只审查当前 Step 的任务、测试结果、Git 变更和潜在风险。Web AI 只给出审查结论，不推进 AgentFlow 状态。

## Required Output

请输出 ReviewResult JSON，必须符合 AgentFlow ReviewResult 协议：

\`\`\`json
{
  "protocolVersion": "agentflow.v1",
  "stepId": "${stepId}",
  "runId": "${runId}",
  "verdict": "approved | changes_required | replan_required | rejected",
  "summary": "...",
  "findings": [
    {
      "severity": "low | medium | high | critical",
      "file": "optional",
      "problem": "...",
      "requiredFix": "optional"
    }
  ],
  "suggestedNextAction": "commit | fix | replan | manual",
  "createdAt": "ISO string"
}
\`\`\`

## Review Criteria

请重点检查：

1. 是否完成 TaskPacket 的 scope。
2. 是否违反 outOfScope。
3. tests.json 是否通过。
4. git diff 是否只包含相关修改。
5. 是否存在敏感文件风险。
6. 是否存在明显代码质量问题。
7. 是否需要 fix 或 replan。

## Sensitive Warnings

${evidence.gitWarnings.length > 0 ? evidence.gitWarnings.map((warning) => `- ${warning}`).join('\n') : '_Not found_'}

## Input Evidence

下面是 AgentFlow 收集的证据：

### TaskPacket

\`\`\`json
${evidence.task}
\`\`\`

### Tests

\`\`\`json
${evidence.tests}
\`\`\`

### Git Evidence

\`\`\`json
${evidence.git}
\`\`\`

### Git Diff

\`\`\`diff
${evidence.diff}
\`\`\`

### Execution Result

\`\`\`json
${evidence.executionResult}
\`\`\`

### Checkpoint Summary

\`\`\`md
${evidence.checkpoint}
\`\`\`

## Safety Rules

- 不要要求读取 .env、密钥、token。
- 不要直接生成代码修改。
- 只输出 ReviewResult JSON，或者先解释后给出 JSON，但 JSON 必须完整。
- 如果证据不足，请在 findings 中说明缺失证据和风险。
`;
}

function isNodeError(error: unknown): error is NodeJS.ErrnoException {
  return error instanceof Error && 'code' in error;
}
