import { PROTOCOL_VERSION, taskPacketSchema, type TaskPacket } from '../protocols/index.js';

export function createInitialTaskPacket(input: {
  stepId: string;
  runId: string;
  goal: string;
  createdAt: string;
}): TaskPacket {
  return taskPacketSchema.parse({
    protocolVersion: PROTOCOL_VERSION,
    stepId: input.stepId,
    runId: input.runId,
    goal: input.goal,
    background: 'Generated by AgentFlow plan command.',
    scope: ['根据目标生成初始任务范围，后续可人工修改。'],
    outOfScope: [],
    contextFiles: ['AGENTS.md', '.agent/generated/context-pack.md'],
    constraints: [
      '不要提交密钥。',
      '不要大范围重构无关代码。',
      '保持现有功能可运行。',
    ],
    acceptanceCommands: ['npm run build'],
    requiresApproval: true,
    createdAt: input.createdAt,
  });
}
