import path from 'node:path';
import { pathExists } from '../utils/fs.js';
import { getAgentDirectory } from '../utils/path.js';
import { getStepDirectory, listRunIds, readStepState, writeText } from '../workflow/step-store.js';
import type { StepState } from '../workflow/step-state.js';
import { buildArtifactConsumption, type ArtifactConsumptionResult } from './artifact-consumption.js';
import { buildArtifactInventory, type ArtifactInventoryItem } from './artifact-inventory.js';
import { buildWorkflowHealth, type WorkflowHealth } from './workflow-health.js';

type WorkflowTimeline = {
  webPlanImported: boolean;
  taskPacketGenerated: boolean;
  executionPromptGenerated: boolean;
  executionResultImported: boolean;
  verificationCompleted: boolean;
  gitEvidenceCollected: boolean;
  webReviewPromptGenerated: boolean;
  reviewResultImported: boolean;
};

export type PilotReportResult = {
  stepId: string;
  reportPath: string;
  runIds: string[];
};

export async function createPilotReport(stepId: string, cwd: string = process.cwd()): Promise<PilotReportResult | undefined> {
  if (!(await pathExists(getAgentDirectory()))) {
    throw new Error('AgentFlow is not initialized. Run `agentflow init` first.');
  }

  const stepDir = getStepDirectory(stepId);
  if (!(await pathExists(stepDir))) return undefined;

  const state = await readStepState(stepId);
  if (!state) {
    throw new Error(`Step state not found: ${toRelativePath(path.join(stepDir, 'state.json'), cwd)}`);
  }

  const runIds = await listRunIds(stepId);
  const inventory = await buildArtifactInventory(stepDir, runIds);
  const consumption = buildArtifactConsumption(inventory);
  const health = buildWorkflowHealth(state, inventory);
  const reportPath = path.join(stepDir, 'pilot-report.md');

  await writeText(reportPath, renderPilotReport({ state, runIds, inventory, consumption, health }));

  return {
    stepId,
    reportPath: toRelativePath(reportPath, cwd),
    runIds,
  };
}

function renderPilotReport(input: {
  state: StepState;
  runIds: string[];
  inventory: ArtifactInventoryItem[];
  consumption: ArtifactConsumptionResult;
  health: WorkflowHealth;
}): string {
  const { state, runIds, inventory, consumption, health } = input;
  const timeline = buildTimeline(state, inventory);
  const generatedAt = new Date().toISOString();

  return `# Pilot Report

> Generated by AgentFlow. Do not edit manually.

Generated At: ${generatedAt}

## 1. Step Overview

- Step ID: ${state.stepId}
- Current Status: ${state.status}
- Current Run: ${state.currentRunId}
- Runs: ${runIds.length > 0 ? runIds.join(', ') : 'none'}
- Goal: ${state.goal}

## 2. Workflow Timeline

- Web Plan imported: ${yesNo(timeline.webPlanImported)}
- TaskPacket generated: ${yesNo(timeline.taskPacketGenerated)}
- Execution prompt generated: ${yesNo(timeline.executionPromptGenerated)}
- ExecutionResult imported: ${yesNo(timeline.executionResultImported)}
- Verification completed: ${yesNo(timeline.verificationCompleted)}
- Git evidence collected: ${yesNo(timeline.gitEvidenceCollected)}
- Web review prompt generated: ${yesNo(timeline.webReviewPromptGenerated)}
- ReviewResult imported: ${yesNo(timeline.reviewResultImported)}
- Final review verdict: ${state.review?.verdict ?? 'missing'}
- Checkpoint status: ${state.checkpoint?.status ?? 'missing'}

## 3. Artifact Inventory

${renderInventory(inventory)}

## 4. Artifact Consumption Map

${consumption.rules.map((rule) => `- ${rule.artifact} -> ${rule.consumedBy.join(' / ')}: ${rule.note}`).join('\n')}

## 5. Framework Health Check

${health.items.map((item) => `- [${item.passed ? 'x' : ' '}] ${item.label}：${item.note}`).join('\n')}
${health.warnings.length > 0 ? `\nWarnings:\n${health.warnings.map((warning) => `- ${warning}`).join('\n')}\n` : ''}
## 6. Manual Friction Points

- 网页端 plan 仍需要手动保存为 Markdown。
- execution-request.md 仍需要手动复制给 Codex/Cursor 等执行器。
- ExecutionResult 仍需要手动保存或整理后导入。
- web-review-request.md 仍需要手动复制给网页 AI / AgentChat skill。
- ReviewResult JSON 仍需要手动保存后导入。
- 自动调用网页 AI: not implemented。
- 自动调用 Codex CLI: not implemented。
- 自动修复 ReviewResult JSON 格式: not implemented。
- 自动 commit: not implemented。

## 7. Redundancy Candidates

${renderRedundancy(consumption.redundancyCandidates)}

## 8. Recommended Next Step

${recommendNextStep(state, consumption.redundancyCandidates)}
`;
}

function buildTimeline(state: StepState, inventory: ArtifactInventoryItem[]): WorkflowTimeline {
  const anyExists = (artifact: string): boolean => inventory.some((item) => item.artifact === artifact && item.status === 'exists');

  return {
    webPlanImported: anyExists('web-plan-source.md'),
    taskPacketGenerated: anyExists('task.json'),
    executionPromptGenerated: anyExists('execution-request.md'),
    executionResultImported: anyExists('execution-result.json') || state.executionResult !== undefined,
    verificationCompleted: anyExists('tests.json') || state.verification !== undefined,
    gitEvidenceCollected: anyExists('git.json') || state.gitCheck !== undefined,
    webReviewPromptGenerated: anyExists('web-review-request.md'),
    reviewResultImported: anyExists('review.json') || state.review !== undefined,
  };
}

function renderInventory(inventory: ArtifactInventoryItem[]): string {
  const rows = inventory.map((item) => `| ${item.runId} | ${item.artifact} | ${item.status} | ${item.purpose} |`);
  return ['| Run | Artifact | Status | Purpose |', '|---|---|---|---|', ...rows].join('\n');
}

function renderRedundancy(candidates: string[]): string {
  if (candidates.length === 0) {
    return '- 暂未发现存在但没有固定消费规则的产物。';
  }

  return candidates.map((candidate) => `- ${candidate}`).join('\n');
}

function recommendNextStep(state: StepState, redundancyCandidates: string[]): string {
  if (state.review?.verdict === 'changes_required' && !state.fixSourceRunId) {
    return '- 当前审查结论是 changes_required，建议优先执行 create-fix，确认修复 run 能继续消费 review.json。';
  }

  if (state.checkpoint?.status === 'blocked') {
    return '- 当前 checkpoint 被阻止，建议先补齐缺失证据或完成修复 run 的 ReviewResult，再进入提交前检查。';
  }

  if (redundancyCandidates.length > 0) {
    return '- 流程已经基本串联，建议下一步根据 Redundancy Candidates 简化人工可读但不驱动状态的产物。';
  }

  return '- 流程整体稳定，建议下一步在保持人工审批边界的前提下，评估 Codex CLI Executor 的最小接入。';
}

function yesNo(value: boolean): 'yes' | 'no' {
  return value ? 'yes' : 'no';
}

function toRelativePath(targetPath: string, cwd: string): string {
  return path.relative(cwd, targetPath).replace(/\\/g, '/');
}
